@startuml
(Python Django Web App) as (WebApp)

note as input
    Index.html: Home; How to Play; Start a new Game; Leaderboards; About Us
    new_game.html: player_name; difficulty_level
    play.html: pencil_marks (true/false); verify_solutions; open scratchpad; close scratchpad
    play.html.scratchpad: [1-9] ON; [1-9] OFF
end note

note as output
    play.html: solution_matches (true/false)
end note

(User) - input
input -> (WebApp)

(WebApp) - output
output -> (User)


@enduml