@startuml

[*] --> InputSubsystem

state InputSubsystem{
}



state FrontEnd{
InputSubsystem --> UserPageSelection
UserPageSelection: Abstract rollup of
UserPageSelection: Index, How to Play,
UserPageSelection: and About
UserPageSelection --> InputSubsystem
InputSubsystem -down-> Leaderboard
Leaderboard -up-> InputSubsystem
InputSubsystem -down-> NewGame: Request NewGame
InputSubsystem -down-> Play
NewGame -up-> InputSubsystem: Returns NewGame.html
NewGame -down-> Play: Set Player name, Set difficulty
Play -up-> InputSubsystem
}


state BackEnd{
Play --> CreateGame
CreateGame --> Play
}

state Database{
Play -->GameRecords
GameRecords -->Leaderboard
@enduml