# Generated by Django 3.0.7 on 2020-06-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='played',
            name='start_time',
        ),
    ]
