# Generated by Django 3.0.6 on 2020-06-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Played',
            fields=[
                ('played_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('saved_board', models.CharField(max_length=1863)),
                ('status', models.CharField(max_length=1)),
                ('hints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('puzzle_id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=1863, unique=True)),
                ('solution', models.CharField(max_length=1863)),
                ('difficulty', models.CharField(max_length=1)),
                ('naked_single', models.BooleanField(default=False)),
                ('hidden_single', models.BooleanField(default=False)),
                ('naked_pair', models.BooleanField(default=False)),
                ('omission', models.BooleanField(default=False)),
                ('naked_triplet', models.BooleanField(default=False)),
                ('hidden_pair', models.BooleanField(default=False)),
                ('naked_quad', models.BooleanField(default=False)),
                ('hidden_triplet', models.BooleanField(default=False)),
                ('hidden_quad', models.BooleanField(default=False)),
                ('x_wing', models.BooleanField(default=False)),
                ('swordfish', models.BooleanField(default=False)),
                ('xy_wing', models.BooleanField(default=False)),
                ('unique_rectangle', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='losses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wins',
            name='id',
        ),
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.DeleteModel(
            name='Losses',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Wins',
        ),
        migrations.AddField(
            model_name='played',
            name='puzzle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoku.Puzzles'),
        ),
    ]
