@startuml
User -> Input: Selects "Start New Game" from Index.html
Input -> new_game: Requests render of newgame.html
new_game-> User: Returns django.shortcuts.render(newgame.html)
User -> Input: Selects "Custom Puzzle" option
Input -> make_game: Requests custom puzzle parameters
make_game -> User: Returns fillable puzzle form
User -> Input: Submits completed custom puzzle form
Input -> make_game: Passes custom puzzle data
make_game -> create_game: Requests custom game creation
create_game -> make_board: Requests 9x9 multidimensional list creation
make_board -> create_game: Returns sudoku board
create_game -> solvable_puzzle: Requests validation that puzzle is solvable
solvable_puzzle -> create_game: Returns whether puzzle is solvable
create_game -> User: If puzzle solvable: Returns django.shortcuts.render(play.html) along with Sudoku board and solution

@enduml