@startuml
User -> Input: Selects "Leaderboard" hyperlink
Input ->findLeaders: Requests render of leaderboard.html
findLeaders -> SQLite_Database: Request table view with top five completions per difficulty
SQLite_Database -> findLeaders: Returns requested records
findLeaders -> User: Returns django.shortcuts.render(leaderboard.html)
User -> Input: Selects a puzzle record to attempt
Input -> make_game: Requests specified leaderboard record puzzle load
make_game -> create_game: Requests game load
create_game -> SQLite_Database: Requests specified puzzle data
SQLite_Database -> create_game: Returns puzzlee data
create_game -> User: Returns specified puzzle
@endumlduml