@startuml
User -> Input: Selects "Start New Game" from Index.html
Input -> new_game: Requests render of newgame.html
new_game-> User: Returns django.shortcuts.render(newgame.html)
User -> Input: Inputs username and selects difficulty
Input -> make_game: POST data passed with username and difficulty selection
make_game -> create_game: Sanitizes input. Requests new game

create_game -> make_board: Requests 9x9 multidimensional list creation
make_board -> create_game: Returns sudoku board
create_game -> hide_cells: Requests cells hidden based on difficulty
hide_cells -> create_game: Returns puzzle solution with hidden cells
create_game -> solvable_puzzle: Requests validation that puzzle can be solved at difficulty level requested
solvable_puzzle -> create_game: Returns whether puzzle is solvable at chosen difficulty
create_game -> User: If puzzle solvable at requested difficulty: Returns django.shortcuts.render(play.html) along with Sudoku board and solution

@enduml